### ISSUE TITLE
Missing /user/allIDs API endpoint in Oryx 1.0.1

### ISSUE THREAD

**Issue by cesarBere** [cloudera/oryx#105]
Hi, 

We've juste switched to Oryx 1.0.1 but there is no `/user/allIDs` API endpoint even if it is defined in the doc ([here](https://github.com/cloudera/oryx/wiki/API-Endpoint-Reference)), was it removed ?

Thanks

**Comment by srowen** [comment]
(You can use the mailing list for questions BTW: https://groups.google.com/a/cloudera.org/forum/#!forum/oryx-user )

This has been added in `master` for 1.0.2, just a few days ago, but is not in 1.0.1. Sorry, this is a case where I wanted to keep the docs in step with the latest code even though that means they're not 100% consistent with the last stable release. 1.0.2 will be coming soon, or you can build from source.
