### ISSUE TITLE
Next Generation (0 MB written) 

### ISSUE THREAD

**Issue by tagline** [cloudera/oryx#118]
Hi, I really would to ask for help.

I've installed Hadoop 2.6 with Yarn and I'm trying to run the example test for Recommendation using Oryx 1.0.

My conf file is like that:

model=${als-model}
model.instance-dir=/home/hduser/oryx/example
#model.local-computation=true
#model.local-data=true
model.local-computation=false
model.local-data=false
model.features=25
model.lambda=0.065

#test.integration=true
serving-layer.api.port=8093
computation-layer.api.port=8094

computation-layer.mapper-memory-mb = 4096
computation-layer.reducer-memory-mb = 4096

And the computation doesn't start. When I try to run the computation layer, the result is like:

Mon Oct 19 12:08:28 CEST 2015 INFO Forcing run -- no complete generations yet
Mon Oct 19 12:08:28 CEST 2015 INFO Connecting to ResourceManager at /0.0.0.0:8032
Mon Oct 19 12:08:28 CEST 2015 INFO Starting run for instance /home/hduser/oryx/example
Mon Oct 19 12:08:28 CEST 2015 INFO No complete generations
Mon Oct 19 12:08:28 CEST 2015 INFO No data in generation 0, so not running
Mon Oct 19 12:08:28 CEST 2015 INFO No need to make a new generation
Mon Oct 19 12:08:28 CEST 2015 INFO No need to wait for a generation
Mon Oct 19 12:08:28 CEST 2015 INFO No generation to run
Mon Oct 19 12:08:30 CEST 2015 INFO Forcing run of PeriodicRunner

**Comment by srowen** [comment]
It sounds like you have not provided any data? that's what it's indicating. If you want it to build a model straight away, you can seed it with data in `00000/inbound`

**Comment by tagline** [comment]
Thanks, for the answer.
I downloaded the file 'audioscrobbler-sample.csv' and store it in dir /home/hduser/oryx/example/00000/inbound

One important question, how better is the Oryx 2.0 about Recommendation?

Thanks

**Comment by srowen** [comment]
These are paths and files on HDFS, right? my next guess is that it's actually looking for a local directory. Although you're correctly asking for distributed storage/compute, is it seeing your Hadoop config locally? You might disambiguate by specifying `hdfs:///home/hduser/...` (three slashes there)

Not sure what you mean by 'better'; the results ought to be pretty similar though the implementation is very different. Generally 2.0.0 is a more complex implementation, but architecturally better in many ways. It requires several Hadoop components though.

**Comment by tagline** [comment]
Ok. So if the results are similar I will continue in 1.0..

I'm for a long long time to run Oryx with Hadoop, but nothing. I already had many and different kind of problems...
Now I decide to run locally, but the application print this (below) and seems that stopped (or complete?) the process!? Although the Computation Layer shows status PENDING. I'm waiting for more than 1 hour. For the data set audioscrobbler-sample.csv, this is normal?

My SO is Ubuntu 14.04, I have 4GB and my processor is a Core i3. And I'm running nothing more, just this Application.

Mon Oct 19 15:05:39 CEST 2015 INFO Initializing ProtocolHandler ["http-nio-8094"]
Mon Oct 19 15:05:39 CEST 2015 INFO Using a shared selector for servlet write/read
Mon Oct 19 15:05:39 CEST 2015 INFO Starting service Tomcat
Mon Oct 19 15:05:39 CEST 2015 INFO Starting Servlet Engine: Apache Tomcat/7.0.63
Mon Oct 19 15:05:39 CEST 2015 INFO At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Mon Oct 19 15:05:39 CEST 2015 INFO Computation Layer console available at http://tagline-530U3C-530U4C-532U3C:8094
Mon Oct 19 15:05:39 CEST 2015 INFO Starting ProtocolHandler ["http-nio-8094"]
Mon Oct 19 15:05:39 CEST 2015 INFO Namespace prefix: file:
Mon Oct 19 15:05:39 CEST 2015 WARNING Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Mon Oct 19 15:05:39 CEST 2015 INFO Forcing run -- no complete generations yet
Mon Oct 19 15:05:40 CEST 2015 INFO Starting run for instance /home/hduser/oryx/example
Mon Oct 19 15:05:40 CEST 2015 INFO No complete generations
Mon Oct 19 15:05:40 CEST 2015 INFO Making new generation 1
Mon Oct 19 15:05:40 CEST 2015 INFO Generation 0 may run immediately
Mon Oct 19 15:05:40 CEST 2015 INFO Running generation 0
Mon Oct 19 15:05:40 CEST 2015 INFO Copying /tmp/1445259940149-0/audioscrobbler-sample.csv to /tmp/1445259940149-1
Mon Oct 19 15:05:40 CEST 2015 INFO Reading /tmp/1445259940149-1/audioscrobbler-sample.csv
Mon Oct 19 15:05:44 CEST 2015 INFO Building factorization...
Mon Oct 19 15:05:44 CEST 2015 INFO Starting from new, random Y matrix
Mon Oct 19 15:05:47 CEST 2015 INFO Constructed initial Y
Mon Oct 19 15:05:47 CEST 2015 INFO Executing ALS with parallelism 4
Mon Oct 19 15:05:52 CEST 2015 INFO Finished iteration 1
Mon Oct 19 15:05:52 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 14670 samples: 0.15108815881408685
Mon Oct 19 15:05:56 CEST 2015 INFO Finished iteration 2
Mon Oct 19 15:05:56 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15568 samples: 0.10959021387717496
Mon Oct 19 15:06:00 CEST 2015 INFO Finished iteration 3
Mon Oct 19 15:06:00 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15306 samples: 0.034227069145467665
Mon Oct 19 15:06:03 CEST 2015 INFO Finished iteration 4
Mon Oct 19 15:06:03 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15119 samples: 0.021324139818332952
Mon Oct 19 15:06:07 CEST 2015 INFO Finished iteration 5
Mon Oct 19 15:06:07 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15057 samples: 0.015582050104184177
Mon Oct 19 15:06:10 CEST 2015 INFO Finished iteration 6
Mon Oct 19 15:06:10 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15093 samples: 0.01220491718965652
Mon Oct 19 15:06:13 CEST 2015 INFO Finished iteration 7
Mon Oct 19 15:06:13 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15140 samples: 0.009876890327979204
Mon Oct 19 15:06:17 CEST 2015 INFO Finished iteration 8
Mon Oct 19 15:06:17 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15150 samples: 0.00818353709671492
Mon Oct 19 15:06:21 CEST 2015 INFO Finished iteration 9
Mon Oct 19 15:06:21 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15156 samples: 0.007021070768983022
Mon Oct 19 15:06:25 CEST 2015 INFO Finished iteration 10
Mon Oct 19 15:06:25 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15147 samples: 0.00615142024673525
Mon Oct 19 15:06:30 CEST 2015 INFO Finished iteration 11
Mon Oct 19 15:06:30 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15093 samples: 0.005491133747021845
Mon Oct 19 15:06:34 CEST 2015 INFO Finished iteration 12
Mon Oct 19 15:06:34 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15117 samples: 0.004962026136496295
Mon Oct 19 15:06:37 CEST 2015 INFO Finished iteration 13
Mon Oct 19 15:06:37 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15112 samples: 0.0044985270606953615
Mon Oct 19 15:06:41 CEST 2015 INFO Finished iteration 14
Mon Oct 19 15:06:41 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15140 samples: 0.004096535505693071
Mon Oct 19 15:06:44 CEST 2015 INFO Finished iteration 15
Mon Oct 19 15:06:44 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15147 samples: 0.0037663061093199625
Mon Oct 19 15:06:48 CEST 2015 INFO Finished iteration 16
Mon Oct 19 15:06:48 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15149 samples: 0.00349824849926203
Mon Oct 19 15:06:52 CEST 2015 INFO Finished iteration 17
Mon Oct 19 15:06:52 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15182 samples: 0.0032559870863716673
Mon Oct 19 15:06:55 CEST 2015 INFO Finished iteration 18
Mon Oct 19 15:06:55 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15189 samples: 0.0030321486382053377
Mon Oct 19 15:06:59 CEST 2015 INFO Finished iteration 19
Mon Oct 19 15:06:59 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15190 samples: 0.002821292560159507
Mon Oct 19 15:07:02 CEST 2015 INFO Finished iteration 20
Mon Oct 19 15:07:02 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15202 samples: 0.0026235993344976504
Mon Oct 19 15:07:06 CEST 2015 INFO Finished iteration 21
Mon Oct 19 15:07:06 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15227 samples: 0.0024437715212819906
Mon Oct 19 15:07:10 CEST 2015 INFO Finished iteration 22
Mon Oct 19 15:07:10 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15243 samples: 0.0022893521302241706
Mon Oct 19 15:07:13 CEST 2015 INFO Finished iteration 23
Mon Oct 19 15:07:13 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15265 samples: 0.002158797117058552
Mon Oct 19 15:07:16 CEST 2015 INFO Finished iteration 24
Mon Oct 19 15:07:16 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15276 samples: 0.002037680848402846
Mon Oct 19 15:07:20 CEST 2015 INFO Finished iteration 25
Mon Oct 19 15:07:20 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15288 samples: 0.0019282436454295972
Mon Oct 19 15:07:23 CEST 2015 INFO Finished iteration 26
Mon Oct 19 15:07:23 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15276 samples: 0.0018320919428267953
Mon Oct 19 15:07:27 CEST 2015 INFO Finished iteration 27
Mon Oct 19 15:07:27 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15275 samples: 0.0017464326891757245
Mon Oct 19 15:07:30 CEST 2015 INFO Finished iteration 28
Mon Oct 19 15:07:30 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15276 samples: 0.0016707428218543801
Mon Oct 19 15:07:34 CEST 2015 INFO Finished iteration 29
Mon Oct 19 15:07:34 CEST 2015 INFO Avg absolute difference in estimate vs prior iteration over 15300 samples: 0.0016033153187993913
Mon Oct 19 15:07:37 CEST 2015 INFO Finished iteration 30
Mon Oct 19 15:07:37 CEST 2015 INFO Reached iteration limit
Mon Oct 19 15:07:37 CEST 2015 INFO Factorization complete
Mon Oct 19 15:07:37 CEST 2015 INFO Writing current input
Mon Oct 19 15:07:37 CEST 2015 INFO Writing input of 73458 entries to /tmp/1445259940150-0/input/0.csv.gz
Mon Oct 19 15:07:40 CEST 2015 INFO Writing known items
Mon Oct 19 15:07:40 CEST 2015 INFO Writing ID-ID map of 73458 entries to /tmp/1445259940150-0/knownItems/0.csv.gz
Mon Oct 19 15:07:42 CEST 2015 INFO Writing X
Mon Oct 19 15:07:42 CEST 2015 INFO Writing ID-float map of 73458 entries to /tmp/1445259940150-0/X/0.csv.gz
Mon Oct 19 15:07:47 CEST 2015 INFO Writing Y
Mon Oct 19 15:07:47 CEST 2015 INFO Writing ID-float map of 47065 entries to /tmp/1445259940150-0/Y/0.csv.gz
Mon Oct 19 15:07:50 CEST 2015 INFO Writing ID mapping
Mon Oct 19 15:07:50 CEST 2015 INFO Writing mapping of 47003 entries to /tmp/1445259940150-0/idMapping/0.csv.gz
Mon Oct 19 15:07:51 CEST 2015 INFO Writing model
Mon Oct 19 15:07:52 CEST 2015 INFO Signaling completion of generation 0
Mon Oct 19 15:07:52 CEST 2015 INFO Dumping some stats on generation 0
Mon Oct 19 15:07:53 CEST 2015 INFO Generation 0 complete

**Comment by srowen** [comment]
Here, you successfully built a model as it says. This is in local mode, I
take it. What is PENDING? eventually another model build job will start,
yes. That's normal.

**Comment by tagline** [comment]
Ok. Because if I access my computation layer (for example: http://localhost:8094/) it shows GENERATION 0 status PENDING, but the End Date is filled, maybe this is a small bug.

Other question, in both cases, running locally and running with Hadoop, how can I see the results? Because in the Documentation I found "The Serving Layer will load its output shortly after it finishes.", but when I try to access the Server Layer (in my case:  http://localhost:8093) I get an error like "Problem to load the page". 
After build the computation and server layers, define the ports on configuration file, it's necessary to do something more?

I also didn't understand how can I ask for some recommendations.
In documentation I found "Use the endpoint interface in the console, input your own preferences". How can I access this interface? It refers about Serving Layer?

Thanks a lot!

**Comment by srowen** [comment]
Are you running the serving layer? it's a separate process.
You'll see the console when you are able to access it.

On Tue, Oct 20, 2015 at 11:49 AM, Tagline Treichel <notifications@github.com

**Comment by tagline** [comment]
Perfect! 

When I get the results, for example:
Tenacious D,1.2511485
Audioslave,1.2081187
Faith No More,1.1865411
Alice in Chains,1.1684613

What this number (second parameter) represents?
Do you have a technical documentation where I can understand the engine (just about Recommendations)?

**Comment by srowen** [comment]
To understand the model, read "Collaborative Filtering for Implicit
Feedback Datasets", which is a pretty standard treatment of the Alternating
Least Squares approach, and one implemented in several tools like Oryx and
MLlib.

http://www.researchgate.net/profile/Yifan_Hu/publication/220765111_Collaborative_Filtering_for_Implicit_Feedback_Datasets/links/0912f509c579ddd954000000.pdf

The score is an estimate of a 0/1 value where 1 corresponds to an
interaction. It can be greater than 1; the highest values are the strongest
recommendations.

On Tue, Oct 20, 2015 at 12:14 PM, Tagline Treichel <notifications@github.com
