### ISSUE TITLE
Can I run Computation-Layer on Hadoop version 0.20.0?

### ISSUE THREAD

**Issue by jiang1983** [cloudera/oryx#120]
For some reasons,I need to run Computation-Layer on Distributed System.
And I have ONLY Hadoop 0.20.2,and I cant reinstall Hadoop.
when I build the projec with "mvn -DskipTests -Dhadoop.version=0.20.0 install",Errors happened which are "Failed to find org.apache.hadoop:hadoop-client:jar:0.20.0 in https://repository.cloudera.com/artifactory/cloudera/cloudera-repos"

Is it means I cant match hadoop 0.20.0 in the repos?
How can I run the Computation-Layer on Hadoop 0.20.0?

THANKS A LOT!!

**Comment by srowen** [comment]
0.20.0 is so old that I don't think it was ever released in Maven Central? I don't see it at least. Certainly that's not a version number you'd find in the Cloudera repo as our versions are like `cdhX.Y.Z...`.

It might work but I doubt it. It's intended for Hadoop 2+.
